before_install:
  - brew update
  - brew upgrade swiftlint
language: objective-c
osx_image: xcode9.3
cache:
  directories:
  - Carthage
script:
  - ./lint.sh
  - ./run_tests.sh
  - ./run_atb_tests.sh
